# This is a basic workflow to help you get started with Actions

name: PKG

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          cd ..
          git clone https://github.com/nativefier/nativefier.git
          cd nativefier
          npm ci
          npx pkg . --targets node16-linux-x64,node16-linux-arm64,node16-win-arm64,node16-win-x64,node16-macos-x64 --no-bytecode --public-packages "*" --public
          ls

      - name: Upload node16-linux-x64
        uses: actions/upload-artifact@v2
        with:
           name: node16-linux-x64
           path: /home/runner/work/nativefier-pkg/nativefier/node16-linux-x64
      - name: Upload node16-linux-arm64
        uses: actions/upload-artifact@v2
        with:
           name: node16-linux-arm64
           path: /home/runner/work/nativefier-pkg/nativefier/node16-linux-arm64
      - name: Upload node16-win-x64
        uses: actions/upload-artifact@v2
        with:
           name: node16-win-x64
           path: /home/runner/work/nativefier-pkg/nativefier/node16-win-x64
      - name: Upload node16-win-arm64
        uses: actions/upload-artifact@v2
        with:
           name: node16-win-arm64
           path: /home/runner/work/nativefier-pkg/nativefier/node16-win-arm64
      - name: Upload node16-macos-x64
        uses: actions/upload-artifact@v2
        with:
           name: node16-macos-x64
           path: /home/runner/work/nativefier-pkg/nativefier/node16-macos-x64
